### ISSUE TITLE
Downgrading firmware?

### ISSUE THREAD

**Issue by bubba925** [janwiesemann/TPLinkSmartPlugMetricExtractor#1]
Well I stumbled on this while deep diving into a fix for my smart switches. I have some HS200/HS210 kasa smart switches that I accidentally upgraded to the latest firmware. I attempted to use them “local” and block internet access but with the new firmware they are set to automatically reconnect to the WiFi if disconnected from the internet. Got any insight on a fix?

**Comment by bubba925** [comment]
Surprisingly via TP Link customer support they contacted their R&D team and are going to revert the changes that break the offline connectivity. They are supplying me with beta OTA firmware until they release this new firmware.

**Comment by bubba925** [comment]
Surprisingly via TP Link customer support they contacted their R&D team and are going to revert the changes that break the offline connectivity. They are supplying me with beta OTA firmware until they release this new firmware.

**Comment by janwiesemann** [comment]
Sorry for my extremely late reply but I've heard on r/HomeAssistant, that tp-link changes this on there firmware. I'm pretty sure a lot of people complained. Personally, I would recommend a isolated VLAN for there smart home stuff and a complete isolation form the Internet. No breaking updates and less spying.
